### ISSUE TITLE
Doesn't seem to work on carts with more than one game

### ISSUE THREAD

**Issue by ajshell1** [IcySon55/NxHashTool#1]
What I did:

Ran "dotnet NxHashTool.dll 'Overboard 1.4.1 [01000CA014CA0000][v262144] + 80 Days 1.0.3 [0100B0700E944000][v196608] (keyarealess) (certless) (untrimmed).xci'

Result: 
```
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.IO.Path.Combine(String path1, String path2)
   at HashTool.Program.Main(String[] args) in V:\Development\HashTool\Program.cs:line 47
zsh: IOT instruction (core dumped)  dotnet NxHashTool.dll
```

I also tried removing the exclamation point in the filename (but it was still in a directory with an exclamation point), but that didn't change the result.o

Also, I can confirm getting good results with a different game

**Comment by IcySon55** [comment]
Hey, thanks for the report. I haven't tried running it using dotnet myself so this will be interesting.

**Comment by mariomadproductions** [comment]
Same running the exe normally on Windows 10.
